-- USE customer_behaviour_analysis;
-- SELECT*FROM customer_analysis LIMIT 5;

-- 1) what is total revenue generated by male vs female customer ?

-- SELECT gender,SUM(purchase_amount) AS Total_Revenue
-- FROM  customer_analysis
-- GROUP BY gender; 

-- 2) which customer used a discount but still spent more than avg purchase amount?

-- SELECT customer_id, purchase_amount FROM 
-- customer_analysis WHERE discount_applied = 'Yes' 
-- AND purchase_amount > (SELECT AVG(purchase_amount)
--  FROM customer_analysis)
--  LIMIT 10;
-- SELECT AVG(purchase_amount)
--  FROM customer_analysis;
 
-- 3) which are top 5 products with the highest avg review rating?

-- SELECT item_purchased,round(AVG(review_rating),2)
-- FROM customer_analysis 
-- group by item_purchased
-- order by AVG(review_rating) desc
-- limit 5;

-- 4) compare the avg purchase amt between standard and express shipping ?

--  SELECT shipping_type, avg(purchase_amount) FROM
--  customer_analysis 
--  where shipping_type in ('Standard', 'Express')
--  group by shipping_type;
 
-- 5) do subscribed customer spend more? cpmare avg spend and total revenue b/w subscriber and non-sub?

--  select count(customer_id) as total_customer,
--  subscription_status, round(avg(purchase_amount),2) 
--  as avg_spend, sum(purchase_amount) AS total_spend
-- from customer_analysis group by  subscription_status
-- order by total_spend,avg_spend desc;

-- 6) which 5 products have highest % of purchase with discounts applied?

-- select item_purchased, round(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2)
-- as dis_rate
-- from customer_analysis
-- group by item_purchased
-- order by dis_rate desc
-- limit 5; 

-- 7) segment customer into new returning and loyal base on their total no. of previous purchase, and show count of each segment.

-- with Customer_Type as(
-- select customer_id, previous_purchases,
-- case
-- when previous_purchases = 1 then 'New'
-- when previous_purchases <10 then 'Returning'
-- else 'Loyal'
-- end AS customer_segment
-- from customer_analysis)

-- select customer_segment,count(*) AS "No. of Customer"
-- from Customer_Type
-- group by customer_segment;

-- 8) what are the top 3 most purchased products with in each category?

 -- with item_count as(
--  select category,item_purchased,
--  count(customer_id) as total_orders,
--  ROW_NUMBER() OVER(PARTITION BY category 
--  order by count(customer_id) desc) AS item_rank
--  from customer_analysis 
--  group by category,item_purchased )
--  
--  SELECT item_rank, category, item_purchased, total_orders
-- FROM item_count
-- WHERE item_rank <= 3;

-- 9) are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

-- select subscription_status,
--  count(customer_id) as total_buyers
--  from customer_analysis
--  where previous_purchases >5
--  group by subscription_status;
 
-- 10) what is the revenue contribution of each age group?
-- select age_group,SUM(purchase_amount) as total_revenue,
-- ROUND(
--         SUM(purchase_amount) * 100.0 / 
--         SUM(SUM(purchase_amount)) OVER (),2)
--         AS revenue_percentage
-- from customer_analysis
-- group by age_group
-- order by sum(purchase_amount) desc;


select 1;